# Generated by Django 4.2.11 on 2024-05-06 19:12

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Accounts', '0003_remove_profile_job_title_profile_user_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('post_cover', models.ImageField(blank=True, null=True, upload_to='blog_images/covers/')),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField()),
                ('content', ckeditor.fields.RichTextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MediaUser',
            fields=[
                ('profile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Accounts.profile')),
            ],
            bases=('Accounts.profile',),
        ),
    ]
