# Generated by Django 4.2.11 on 2024-08-05 16:37

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models
import website.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("Accounts", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("url", models.SlugField(max_length=60, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="BlogPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "post_cover",
                    models.ImageField(
                        blank=True, null=True, upload_to=website.models.upload_pic_blog
                    ),
                ),
                ("pub_date", models.DateTimeField(auto_now_add=True)),
                ("slug", models.SlugField(allow_unicode=True)),
                ("published", models.BooleanField(default=True)),
                ("body", tinymce.models.HTMLField(blank=True, null=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="website.category",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_blog_post",
                        to="Accounts.mediaprofile",
                    ),
                ),
            ],
        ),
    ]
