# Generated by Django 4.2.11 on 2024-05-07 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_alter_blogpost_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='content',
            new_name='body',
        ),
    ]
