# Generated by Django 4.2.11 on 2024-05-07 17:05

from django.db import migrations, models
import tinymce.models
import website.models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_category_blogpost_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='body',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='post_cover',
            field=models.ImageField(blank=True, null=True, upload_to=website.models.upload_pic_blog),
        ),
    ]
