# Generated by Django 4.2.11 on 2024-04-19 17:04

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profile_Media_Admin',
            new_name='Profile',
        ),
    ]
