# Generated by Django 4.2.11 on 2024-04-21 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0002_rename_profile_media_admin_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='job_title',
        ),
        migrations.AddField(
            model_name='profile',
            name='user_type',
            field=models.CharField(choices=[('student', 'طالب'), ('teacher', 'محاضر'), ('staff', 'موظفين')], default='student', max_length=20),
        ),
    ]
