# Generated by Django 4.2.11 on 2024-08-23 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Accounts", "0003_lecturerprofile_academic_specialization_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="nationality",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
