# Generated by Django 4.2.11 on 2024-08-07 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="subject",
            name="sub_id",
            field=models.CharField(default=None, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="major",
            name="department",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="major_deparment",
                to="courses.department",
            ),
        ),
        migrations.AlterField(
            model_name="subject",
            name="name_ar",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="subject",
            name="name_en",
            field=models.CharField(max_length=50),
        ),
    ]
